title: Pragmatic Unity Game Development
author: Leon Arndt
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Pragmatic tips for making games in Unity

# social links
github_username:  leon-arndt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
